### ISSUE TITLE
Empty black space in emulator window

### ISSUE THREAD

**Issue by MrReilley** [shftgroup/gisst#114]
When running games on the emulation screen, an empty, black space consistently appears on the right-hand side of the emulator window. This issue persists regardless of the game or console being emulated.

![BUG](https://github.com/shftgroup/gisst/assets/50684808/13438b08-a16f-4bfa-bf6d-81c769b86f91)

**Comment by ekaltman** [comment]
Closing this issue as it's an easy fix with the background color CSS in the UI and we are changing the UI so I'm not going to fix this.
