### ISSUE TITLE
Unable to edit the title or description of a state booted from the instance link screen

### ISSUE THREAD

**Issue by MrReilley** [shftgroup/gisst#117]
The edit functionality for the title and description is disabled for game states that are accessed and booted through the Instance Link screen. This issue is specific to the state booted into, and other states that are created once in the emulator page are editable.

Steps to Reproduce:
1. Start the emulator and boot into a game.
2. Save a current game state and upload it to the server.
3. Go to the Instance Link page for the recently uploaded game.
4. Click on the "Boot" button next to the corresponding saved state.
5. Navigate to the States Tab.
6. Attempt to click the edit state_name/state_description button on the booted into state.

**Comment by ekaltman** [comment]
Once states or performances are saved to the server their descriptive information cannot be edited. This is because they may be embedded. I think maybe we could allow the citations creator to edit or update the description?

**Comment by ekaltman** [comment]
Closed and referred to #159
