### ISSUE TITLE
Emulation screen malfunctions after letting a performance finish replaying 

### ISSUE THREAD

**Issue by MrReilley** [shftgroup/gisst#118]
After a performance finishes replaying, the emulator screen freezes, and general functionality malfunctions in the following ways:

Saving a state from the frozen emulation state, then attempting to load into it, causes the emulator screen to turn black and become unresponsive. 

Pressing the replay button on the performance that just finished causes the emulator screen to turn black and become unresponsive. 

The edit state_name/state_description button on the performance that just finished is disabled. 

Steps to Reproduce:
1. Start the emulator and boot into a game
2. Start and finish a performance 
3. Go to the Performances tab and press play button on recorded performance
4. Let performance play until it finishes

**Comment by ekaltman** [comment]
Is this is v86 or retro arch emulations? In retroarch the emulator is automatically paused after a performance finishes, unpausing requires hitting "P". I will add an issue to add this information to the Info tab.
