### ISSUE TITLE
Checkpoints are not saved with their performances

### ISSUE THREAD

**Issue by MrReilley** [shftgroup/gisst#120]
Any performance that is uploaded does not save its checkpoints with it. When a performance that is saved is booted into, the checkpoint tab and even state tab are empty.

Steps to Reproduce:
1. Start the emulator and boot into a game
2. Click start performance
3. Save a few states 
4. Upload the performance 
5. Navigate to the Instance Link page for the uploaded performance
6. Boot into the performance
8. Check the checkpoints tab

**Comment by ekaltman** [comment]
Checkpoints will only appear when a replay is being played. Checkpoints are implicitly save with their performances. Adding an issue to allow for viewing checkpoints when a replay is not being played in #124.
