### ISSUE TITLE
Pressing the replay button on performance very quickly causes the border color to change between red and green

### ISSUE THREAD

**Issue by MrReilley** [shftgroup/gisst#121]
When viewing a previously recorded performance in the performance tab, if you press the replay button on a previously recorded performance in the performance tab very quickly, it will cause the border color to change to red for a few moments instead of green. 

Steps to Reproduce:
1. Start the emulator and boot into a game
2. Press start performance, then after a few movements press finish performance
3. Go to the performance tab
4. Press the replay button on the recorded performance quickly for a few seconds

**Comment by ekaltman** [comment]
Closed as a issue with the legacy UI.
