### ISSUE TITLE
Capture mouse 

### ISSUE THREAD

**Issue by ekaltman** [shftgroup/gisst#140]
We need to capture the mouse when clicking on the emulator window. Otherwise, it is difficult to get the mouse cursor in the correct position in multiple OSes / programs.

**Comment by JoeOsborn** [comment]
What should the UI be for releasing the mouse?  e.g. in order to click certain buttons in the GISST UI.  I'm especially concerned about the "stop recording" button if the mouse capture is necessary for the recording to work properly.

**Comment by JoeOsborn** [comment]
The browser tells the user what to do, it's hitting the ESC key. If you need to hit ESC in your windows program you can still interact normally after pressing ESC (including pressing ESC again), you just don't have a captured mouse until clicking again.  it's a little awkward to use if you *don't* want capture at all, but...
