### ISSUE TITLE
make a copy of a state/replay with a new name/description

### ISSUE THREAD

**Issue by JoeOsborn** [shftgroup/gisst#159]
In general, but especially now that I'm seeing my states on the creator page, it would be really useful to be able to modify the label and description of past states and replays I've made.  Maybe on a /state/ page or a /replay/ page?

**Comment by ekaltman** [comment]
There is the issue of access to the edits, like we'll need user roles

**Comment by ekaltman** [comment]
The tracking branch for this issue is now very behind. I'm going to shelve this until the UI and backend modifications for dumps and constant recording are implemented.

**Comment by JoeOsborn** [comment]
So this is going to instead be, "make a copy of this state with a new name/description" and so on
