### ISSUE TITLE
New environment/instance split

### ISSUE THREAD

**Issue by JoeOsborn** [shftgroup/gisst#31]
Per discord discussion, we want something like "an instance is bfight.nes and an environment is 'bfight.nes on fceumm configured like so'".  This way we can say an instance of a DOS game is the DOS game's installer or binary files or whatever (linked via objects) and its environment is a v86 or dosbox setup with that all configured.

**Comment by ekaltman** [comment]
Closing this as we have moved on a bit in this discussion due to #165 and current UI changes.
