### ISSUE TITLE
Change URL scheme for /play and gisst://

### ISSUE THREAD

**Issue by JoeOsborn** [shftgroup/gisst#36]
Instead of query parameters:

`gisst://host/{env|state|replay}/UUID`
`https://host/play/{env|state|replay}/UUID`

**Comment by ekaltman** [comment]
@JoeOsborn did you still want to change this? I think we'd also need a redirect to preserve some of the student content links that have been already created.

**Comment by JoeOsborn** [comment]
We can always revise this later, but I agree about preserving back compat.  Here’s an idea:
If there is a parameter we should use its uuid and figure out the right instance (or throw an error if its instance differs from the url path component) or else if there’s no param we just pull up the given database resource (a replay, a state, an instance, later on a workspace) and figure out the right instance from there

**Comment by ekaltman** [comment]
Closing this as we are working on a new scheme for the new UI routing.
